baseURL = "https://python-sdk-etdi.github.io"
languageCode = "en-us"
title = "ETDI Security Framework"
description = "Enhanced Tool Definition Interface - Advanced Security for AI Tool Interactions"

theme = ["hextra"]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.112.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    lineNos = true
    lineNumbersInTable = false

[menu]
  [[menu.main]]
    name = "Documentation"
    pageRef = "/docs"
    weight = 10

  [[menu.main]]
    name = "Examples"
    pageRef = "/examples"
    weight = 20

  [[menu.main]]
    name = "API Reference"
    pageRef = "/api"
    weight = 30

[params]
  navbar.displayTitle = true
  navbar.displayLogo = false
  footer.displayCopyright = true
  footer.displayPoweredBy = false
  editPage.enable = true
  editPage.base = "https://github.com/python-sdk-etdi/python-sdk-etdi"
  search.enable = true
  search.type = "flexsearch"
  [params.hextra]
    [params.hextra.navbar]
      [params.hextra.navbar.logo]
        path = "images/logo.svg"
        link = "/"
        width = 30
        height = 30 