name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
  pull_request:
    branches:
      - main # Or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Match your project's Python version
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install .[docs]

      - name: Build MkDocs site
        run: |
          mkdocs build --clean

      - name: Create .nojekyll file
        run: |
          touch site/.nojekyll # Create .nojekyll in the site output directory

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
          # The --force flag is used to overwrite the existing gh-pages branch
          # Ensure your GitHub Pages settings are configured to deploy from the gh-pages branch 